# Generated by Django 5.2.15 on 2026-06-11 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('goal', models.CharField(choices=[('lose', 'Lose Weight'), ('gain', 'Gain Weight'), ('maintain', 'Maintain Weight')], default='maintain', max_length=20)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=20)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Centimeters', max_digits=5, null=True)),
                ('current_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Kilograms', max_digits=5, null=True)),
                ('activity_level', models.CharField(choices=[('no_activity', 'No Activity'), ('normal_walk', 'Normal Walk'), ('light_active', 'Gym / Light Active'), ('very_active', 'Very Active')], default='normal_walk', max_length=30)),
                ('daily_calorie_goal', models.PositiveIntegerField(default=0)),
                ('protein_goal', models.PositiveIntegerField(default=0)),
                ('carbs_goal', models.PositiveIntegerField(default=0)),
                ('fat_goal', models.PositiveIntegerField(default=0)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__id'],
            },
        ),
    ]
