# Generated by Django 5.2.15 on 2026-06-11 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('dinner', 'Dinner')], max_length=20)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount_type', models.CharField(choices=[('grams', 'Grams'), ('quantity', 'Quantity')], default='grams', max_length=20)),
                ('calories', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('carbs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_entries', to='foods.fooditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'meal_type', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='meals_meale_user_id_fc2f10_idx'), models.Index(fields=['user', 'meal_type', 'date'], name='meals_meale_user_id_3e50cf_idx')],
            },
        ),
    ]
