# Generated by Django 5.2.15 on 2026-06-11 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'food categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160)),
                ('serving_type', models.CharField(choices=[('grams', 'Per 100g'), ('quantity', 'Per Quantity')], default='grams', max_length=20)),
                ('quantity_label', models.CharField(blank=True, default='', max_length=60)),
                ('icon', models.CharField(blank=True, default='', max_length=80)),
                ('serving_size_grams', models.DecimalField(decimal_places=2, default=100, max_digits=7)),
                ('calories', models.DecimalField(decimal_places=2, help_text='Calories per 100g or per quantity', max_digits=8)),
                ('protein', models.DecimalField(decimal_places=2, default=0, help_text='Protein grams per 100g or per quantity', max_digits=8)),
                ('carbs', models.DecimalField(decimal_places=2, default=0, help_text='Carbs grams per 100g or per quantity', max_digits=8)),
                ('fat', models.DecimalField(decimal_places=2, default=0, help_text='Fat grams per 100g or per quantity', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='foods.foodcategory')),
            ],
            options={
                'ordering': ['category__name', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
    ]
